TASK [../roles/database-init : Wait for RDS to be available] ********************************************************
fatal: [ec2-35-169-60-63.compute-1.amazonaws.com]: FAILED! => {"attempts": 1, "changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>", "redirected": false, "status": -1, "url": "https://homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432"}
...ignoring
TASK [../roles/database-init : Store application passwords in Secrets Manager] **************************************
failed: [ec2-35-169-60-63.compute-1.amazonaws.com] (item=vaultwarden) => {"ansible_loop_var": "item", "changed": true, "cmd": "aws secretsmanager create-secret  --name \"homelab-dev-vaultwarden-db\"  --description \"Database credentials for vaultwarden\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\", \n    \"database\": \"vaultwarden\",\n    \"username\": \"vaultwarden\",\n    \"password\": \"YHd0iwyTug9i7trKewsuv85HMHV5BZ0m\",\n    \"url\": \"postgresql://vaultwarden:YHd0iwyTug9i7trKewsuv85HMHV5BZ0m@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/vaultwarden\"\n  }' || aws secretsmanager update-secret  --secret-id \"homelab-dev-vaultwarden-db\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\",\n    \"database\": \"vaultwarden\",\n    \"username\": \"vaultwarden\",\n    \"password\": \"YHd0iwyTug9i7trKewsuv85HMHV5BZ0m\",\n    \"url\": \"postgresql://vaultwarden:YHd0iwyTug9i7trKewsuv85HMHV5BZ0m@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/vaultwarden\"\n  }'\n", "delta": "0:00:02.863066", "end": "2025-07-28 13:30:05.787758", "item": "vaultwarden", "msg": "non-zero return code", "rc": 254, "start": "2025-07-28 13:30:02.924692", "stderr": "\nAn error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-vaultwarden-db because no identity-based policy allows the secretsmanager:CreateSecret action\n\nAn error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-vaultwarden-db because no identity-based policy allows the secretsmanager:UpdateSecret action", "stderr_lines": ["", "An error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-vaultwarden-db because no identity-based policy allows the secretsmanager:CreateSecret action", "", "An error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-vaultwarden-db because no identity-based policy allows the secretsmanager:UpdateSecret action"], "stdout": "", "stdout_lines": []}
failed: [ec2-35-169-60-63.compute-1.amazonaws.com] (item=nextcloud) => {"ansible_loop_var": "item", "changed": true, "cmd": "aws secretsmanager create-secret  --name \"homelab-dev-nextcloud-db\"  --description \"Database credentials for nextcloud\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\", \n    \"database\": \"nextcloud\",\n    \"username\": \"nextcloud\",\n    \"password\": \"K4QmESApdG6fAV2FAnSENbriV2LwF7ia\",\n    \"url\": \"postgresql://nextcloud:K4QmESApdG6fAV2FAnSENbriV2LwF7ia@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/nextcloud\"\n  }' || aws secretsmanager update-secret  --secret-id \"homelab-dev-nextcloud-db\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\",\n    \"database\": \"nextcloud\",\n    \"username\": \"nextcloud\",\n    \"password\": \"K4QmESApdG6fAV2FAnSENbriV2LwF7ia\",\n    \"url\": \"postgresql://nextcloud:K4QmESApdG6fAV2FAnSENbriV2LwF7ia@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/nextcloud\"\n  }'\n", "delta": "0:00:02.724058", "end": "2025-07-28 13:30:11.989887", "item": "nextcloud", "msg": "non-zero return code", "rc": 254, "start": "2025-07-28 13:30:09.265829", "stderr": "\nAn error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-nextcloud-db because no identity-based policy allows the secretsmanager:CreateSecret action\n\nAn error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-nextcloud-db because no identity-based policy allows the secretsmanager:UpdateSecret action", "stderr_lines": ["", "An error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-nextcloud-db because no identity-based policy allows the secretsmanager:CreateSecret action", "", "An error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-nextcloud-db because no identity-based policy allows the secretsmanager:UpdateSecret action"], "stdout": "", "stdout_lines": []}
failed: [ec2-35-169-60-63.compute-1.amazonaws.com] (item=grafana) => {"ansible_loop_var": "item", "changed": true, "cmd": "aws secretsmanager create-secret  --name \"homelab-dev-grafana-db\"  --description \"Database credentials for grafana\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\", \n    \"database\": \"grafana\",\n    \"username\": \"grafana\",\n    \"password\": \"isQ4IeO9ajl93YmejTeClyu5Ksmqz7iJ\",\n    \"url\": \"postgresql://grafana:isQ4IeO9ajl93YmejTeClyu5Ksmqz7iJ@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/grafana\"\n  }' || aws secretsmanager update-secret  --secret-id \"homelab-dev-grafana-db\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\",\n    \"database\": \"grafana\",\n    \"username\": \"grafana\",\n    \"password\": \"isQ4IeO9ajl93YmejTeClyu5Ksmqz7iJ\",\n    \"url\": \"postgresql://grafana:isQ4IeO9ajl93YmejTeClyu5Ksmqz7iJ@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/grafana\"\n  }'\n", "delta": "0:00:02.643858", "end": "2025-07-28 13:30:18.077764", "item": "grafana", "msg": "non-zero return code", "rc": 254, "start": "2025-07-28 13:30:15.433906", "stderr": "\nAn error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-grafana-db because no identity-based policy allows the secretsmanager:CreateSecret action\n\nAn error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-grafana-db because no identity-based policy allows the secretsmanager:UpdateSecret action", "stderr_lines": ["", "An error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-grafana-db because no identity-based policy allows the secretsmanager:CreateSecret action", "", "An error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-grafana-db because no identity-based policy allows the secretsmanager:UpdateSecret action"], "stdout": "", "stdout_lines": []}
failed: [ec2-35-169-60-63.compute-1.amazonaws.com] (item=jenkins) => {"ansible_loop_var": "item", "changed": true, "cmd": "aws secretsmanager create-secret  --name \"homelab-dev-jenkins-db\"  --description \"Database credentials for jenkins\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\", \n    \"database\": \"jenkins\",\n    \"username\": \"jenkins\",\n    \"password\": \"aYkoydSR5E5GDKy7OlVIkXBLjRb89jLD\",\n    \"url\": \"postgresql://jenkins:aYkoydSR5E5GDKy7OlVIkXBLjRb89jLD@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/jenkins\"\n  }' || aws secretsmanager update-secret  --secret-id \"homelab-dev-jenkins-db\"  --secret-string '{\n    \"host\": \"homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com\",\n    \"port\": \"5432\",\n    \"database\": \"jenkins\",\n    \"username\": \"jenkins\",\n    \"password\": \"aYkoydSR5E5GDKy7OlVIkXBLjRb89jLD\",\n    \"url\": \"postgresql://jenkins:aYkoydSR5E5GDKy7OlVIkXBLjRb89jLD@homelab-dev-postgres.cu3sw4eky9tq.us-east-1.rds.amazonaws.com:5432/jenkins\"\n  }'\n", "delta": "0:00:02.515819", "end": "2025-07-28 13:30:24.037294", "item": "jenkins", "msg": "non-zero return code", "rc": 254, "start": "2025-07-28 13:30:21.521475", "stderr": "\nAn error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-jenkins-db because no identity-based policy allows the secretsmanager:CreateSecret action\n\nAn error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-jenkins-db because no identity-based policy allows the secretsmanager:UpdateSecret action", "stderr_lines": ["", "An error occurred (AccessDeniedException) when calling the CreateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:CreateSecret on resource: homelab-dev-jenkins-db because no identity-based policy allows the secretsmanager:CreateSecret action", "", "An error occurred (AccessDeniedException) when calling the UpdateSecret operation: User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-0294a9a53914d7ca1 is not authorized to perform: secretsmanager:UpdateSecret on resource: homelab-dev-jenkins-db because no identity-based policy allows the secretsmanager:UpdateSecret action"], "stdout": "", "stdout_lines": []}