ubuntu@ip-10-0-1-113:~$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

ubuntu@ip-10-0-1-113:~$ kubectl get pods -n homelab
NAME                           READY   STATUS             RESTARTS      AGE
caddy-77b968dbc7-prpck         1/1     Running            1 (10m ago)   14m
grafana-64b85957b4-zdbkr       0/1     CrashLoopBackOff   4 (57s ago)   14m
jenkins-d59f7d7b7-vfzr2        1/1     Running            1 (10m ago)   14m
nextcloud-768d58ccfc-9n4r2     1/1     Running            2 (10m ago)   14m
node-exporter-2xvjp            1/1     Running            1 (10m ago)   14m
prometheus-b557fdf45-wfsnv     1/1     Running            1 (10m ago)   14m
redis-7484b96d6c-bzw7r         1/1     Running            1 (10m ago)   14m
vaultwarden-6bc665c5fb-nn57w   1/1     Running            1 (10m ago)   14m
ubuntu@ip-10-0-1-113:~$ kubectl get svc -n homelab
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                     AGE
caddy           NodePort    10.106.203.173   <none>        80:30080/TCP,443:30443/TCP,2019:30019/TCP   14m
grafana         ClusterIP   10.96.41.9       <none>        3000/TCP                                    14m
jenkins         ClusterIP   10.101.152.182   <none>        8080/TCP,50000/TCP                          14m
nextcloud       ClusterIP   10.108.201.77    <none>        80/TCP                                      14m
node-exporter   ClusterIP   10.108.233.180   <none>        9100/TCP                                    14m
prometheus      ClusterIP   10.109.11.72     <none>        9090/TCP                                    14m
redis           ClusterIP   10.111.156.181   <none>        6379/TCP                                    14m
vaultwarden     ClusterIP   10.108.234.166   <none>        80/TCP,3012/TCP                             14m
ubuntu@ip-10-0-1-113:~$ kubectl get svc caddy -n homelab -o wide
NAME    TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                                     AGE   SELECTOR
caddy   NodePort   10.106.203.173   <none>        80:30080/TCP,443:30443/TCP,2019:30019/TCP   14m   app=caddy
ubuntu@ip-10-0-1-113:~$ sudo iptables -t nat -L PREROUTING -n --line-numbers
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 /* Redirect 80 to NodePort 30080 */ redir ports 30080
2    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 /* Redirect 443 to NodePort 30443 */ redir ports 30443
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 30080
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 30443
5    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
ubuntu@ip-10-0-1-113:~$ sudo iptables -t nat -L PREROUTING | grep -E "(30080|30443)"
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http /* Redirect 80 to NodePort 30080 */ redir ports 30080
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https /* Redirect 443 to NodePort 30443 */ redir ports 30443
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http redir ports 30080
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 30443
ubuntu@ip-10-0-1-113:~$ curl -I http://localhost:30080
curl -I http://localhost:30443
curl: (7) Failed to connect to localhost port 30080 after 0 ms: Connection refused
curl: (7) Failed to connect to localhost port 30443 after 0 ms: Connection refused
ubuntu@ip-10-0-1-113:~$ kubectl logs -n homelab deployment/caddy
{"level":"info","ts":1754912006.1454859,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
{"level":"info","ts":1754912006.1479526,"msg":"adapted config to JSON","adapter":"caddyfile"}
{"level":"warn","ts":1754912006.1480262,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1754912006.1486874,"msg":"redirected default logger","from":"stderr","to":"stdout"}
{"level":"info","ts":1754912006.1588063,"logger":"admin","msg":"admin endpoint started","address":"0.0.0.0:2019","enforce_origin":false,"origins":["//0.0.0.0:2019"]}
{"level":"warn","ts":1754912006.1589005,"logger":"admin","msg":"admin endpoint on open interface; host checking disabled","address":"0.0.0.0:2019"}
{"level":"info","ts":1754912006.1591089,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1754912006.1591365,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1754912006.1596859,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
{"level":"info","ts":1754912006.1597402,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
{"level":"info","ts":1754912006.1597958,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
{"level":"info","ts":1754912006.159918,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1754912006.1599247,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["passwords.avigdol.com","jenkins.avigdol.com","monitor.avigdol.com","files.avigdol.com"]}
{"level":"info","ts":1754912006.1601677,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1754912006.1602364,"msg":"serving initial configuration"}
{"level":"info","ts":1754912006.160526,"logger":"tls.obtain","msg":"acquiring lock","identifier":"passwords.avigdol.com"}
{"level":"info","ts":1754912006.163889,"logger":"tls.obtain","msg":"lock acquired","identifier":"passwords.avigdol.com"}
{"level":"info","ts":1754912006.163954,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"passwords.avigdol.com"}
{"level":"info","ts":1754912006.16441,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["passwords.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.164429,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["passwords.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1644418,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.166454,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003cd400"}
{"level":"info","ts":1754912006.1705506,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"273167bf-c9aa-4b61-8cf0-ed90e2a9c4c8","try_again":1754998406.170549,"try_again_in":86399.99999968}
{"level":"info","ts":1754912006.170648,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1754912006.174412,"logger":"tls.obtain","msg":"acquiring lock","identifier":"jenkins.avigdol.com"}
{"level":"info","ts":1754912006.178965,"logger":"tls.obtain","msg":"lock acquired","identifier":"jenkins.avigdol.com"}
{"level":"info","ts":1754912006.1802194,"logger":"tls.obtain","msg":"acquiring lock","identifier":"monitor.avigdol.com"}
{"level":"info","ts":1754912006.185228,"logger":"tls.obtain","msg":"lock acquired","identifier":"monitor.avigdol.com"}
{"level":"info","ts":1754912006.1853473,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"monitor.avigdol.com"}
{"level":"info","ts":1754912006.1882622,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["monitor.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1887429,"logger":"tls.obtain","msg":"acquiring lock","identifier":"files.avigdol.com"}
{"level":"info","ts":1754912006.1922984,"logger":"tls.obtain","msg":"lock acquired","identifier":"files.avigdol.com"}
{"level":"info","ts":1754912006.192486,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"files.avigdol.com"}
{"level":"info","ts":1754912006.1931756,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["files.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1952207,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"jenkins.avigdol.com"}
{"level":"info","ts":1754912006.195963,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["jenkins.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1960285,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["jenkins.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1961026,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.1961312,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["monitor.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1961427,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.1961474,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["files.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.196158,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912011.2420242,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912011.4947605,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912011.7476187,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912011.7476785,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"passwords.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912011.7477486,"logger":"tls.obtain","msg":"will retry","error":"[passwords.avigdol.com] Obtain: [passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":5.583843988,"max_duration":2592000}
{"level":"warn","ts":1754912011.7497356,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.0051472,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.2595048,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912012.259611,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"jenkins.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912012.259907,"logger":"tls.obtain","msg":"will retry","error":"[jenkins.avigdol.com] Obtain: [jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":6.080840724,"max_duration":2592000}
{"level":"warn","ts":1754912012.26359,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.5166016,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.7697346,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912012.769786,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"monitor.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912012.769857,"logger":"tls.obtain","msg":"will retry","error":"[monitor.avigdol.com] Obtain: [monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":6.584598628,"max_duration":2592000}
{"level":"warn","ts":1754912012.7718956,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912013.0246785,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912013.2778504,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912013.2779024,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"files.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912013.2779446,"logger":"tls.obtain","msg":"will retry","error":"[files.avigdol.com] Obtain: [files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":7.085547067,"max_duration":2592000}
{"level":"info","ts":1754912038.356297,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"47522","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912048.3568954,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"58040","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912058.3564491,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"54260","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912068.356853,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"40822","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912071.7479272,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"passwords.avigdol.com"}
{"level":"info","ts":1754912071.7483563,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912071.7534273,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.0071354,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.2599964,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912072.2600498,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"passwords.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912072.260094,"logger":"tls.obtain","msg":"will retry","error":"[passwords.avigdol.com] Obtain: [passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":66.096189846,"max_duration":2592000}
{"level":"info","ts":1754912072.260208,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"jenkins.avigdol.com"}
{"level":"info","ts":1754912072.2605584,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912072.2625935,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.5153475,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.768038,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912072.7680888,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"jenkins.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912072.7681289,"logger":"tls.obtain","msg":"will retry","error":"[jenkins.avigdol.com] Obtain: [jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":66.589063289,"max_duration":2592000}
{"level":"info","ts":1754912072.7703786,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"monitor.avigdol.com"}
{"level":"info","ts":1754912072.7707348,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912072.7729354,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.0257215,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"info","ts":1754912073.2781935,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"files.avigdol.com"}
{"level":"info","ts":1754912073.2786655,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912073.2790303,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912073.2790961,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"monitor.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912073.2791479,"logger":"tls.obtain","msg":"will retry","error":"[monitor.avigdol.com] Obtain: [monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":67.093889213,"max_duration":2592000}
{"level":"warn","ts":1754912073.2823973,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.5354142,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.7883143,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912073.7883706,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"files.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912073.7884212,"logger":"tls.obtain","msg":"will retry","error":"[files.avigdol.com] Obtain: [files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":67.596023469,"max_duration":2592000}
{"level":"info","ts":1754912078.3568552,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"51854","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912085.9622822,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"36212","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912088.3564672,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"36220","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912098.3563492,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"57828","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912108.356907,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"47652","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912115.9619389,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"52386","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912118.3562896,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"52392","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912128.3566787,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"51442","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912138.3570406,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"52730","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912145.9621224,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"53624","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912148.356563,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"53626","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912158.3570757,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"52914","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912168.3566906,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"42762","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
{"level":"info","ts":1754912175.9622045,"logger":"admin.api","msg":"received request","method":"GET","host":"10.244.0.23:2019","uri":"/config/","remote_ip":"10.244.0.1","remote_port":"57166","headers":{"Accept":["*/*"],"Connection":["close"],"User-Agent":["kube-probe/1.33"]}}
ubuntu@ip-10-0-1-113:~$ kubectl logs -n homelab deployment/caddy | grep -i acme
{"level":"info","ts":1754912006.16441,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["passwords.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.164429,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["passwords.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1644418,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.1882622,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["monitor.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1931756,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["files.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.195963,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["jenkins.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1960285,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["jenkins.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1961026,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.1961312,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["monitor.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.1961427,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"info","ts":1754912006.1961474,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["files.avigdol.com"],"ca":"https://acme-staging-v02.api.letsencrypt.org/directory","account":"admin@avigdol.com"}
{"level":"info","ts":1754912006.196158,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912011.2420242,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912011.4947605,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912011.7476187,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912011.7476785,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"passwords.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912011.7477486,"logger":"tls.obtain","msg":"will retry","error":"[passwords.avigdol.com] Obtain: [passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":5.583843988,"max_duration":2592000}
{"level":"warn","ts":1754912011.7497356,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.0051472,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.2595048,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912012.259611,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"jenkins.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912012.259907,"logger":"tls.obtain","msg":"will retry","error":"[jenkins.avigdol.com] Obtain: [jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":6.080840724,"max_duration":2592000}
{"level":"warn","ts":1754912012.26359,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.5166016,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912012.7697346,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912012.769786,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"monitor.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912012.769857,"logger":"tls.obtain","msg":"will retry","error":"[monitor.avigdol.com] Obtain: [monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":6.584598628,"max_duration":2592000}
{"level":"warn","ts":1754912012.7718956,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912013.0246785,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912013.2778504,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912013.2779024,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"files.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912013.2779446,"logger":"tls.obtain","msg":"will retry","error":"[files.avigdol.com] Obtain: [files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":1,"retrying_in":60,"elapsed":7.085547067,"max_duration":2592000}
{"level":"info","ts":1754912071.7483563,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912071.7534273,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.0071354,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.2599964,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912072.2600498,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"passwords.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912072.260094,"logger":"tls.obtain","msg":"will retry","error":"[passwords.avigdol.com] Obtain: [passwords.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":66.096189846,"max_duration":2592000}
{"level":"info","ts":1754912072.2605584,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912072.2625935,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.5153475,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912072.768038,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912072.7680888,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"jenkins.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912072.7681289,"logger":"tls.obtain","msg":"will retry","error":"[jenkins.avigdol.com] Obtain: [jenkins.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":66.589063289,"max_duration":2592000}
{"level":"info","ts":1754912072.7707348,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912072.7729354,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.0257215,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"info","ts":1754912073.2786655,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://acme-staging-v02.api.letsencrypt.org/acme/acct/219860843","account_contact":["mailto:admin@avigdol.com"]}
{"level":"warn","ts":1754912073.2790303,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912073.2790961,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"monitor.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912073.2791479,"logger":"tls.obtain","msg":"will retry","error":"[monitor.avigdol.com] Obtain: [monitor.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":67.093889213,"max_duration":2592000}
{"level":"warn","ts":1754912073.2823973,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.5354142,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"warn","ts":1754912073.7883143,"logger":"tls.issuance.acme.acme_client","msg":"HTTP request failed; retrying","url":"https://acme-staging-v02.api.letsencrypt.org/directory","error":"performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused"}
{"level":"error","ts":1754912073.7883706,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"files.avigdol.com","issuer":"acme-staging-v02.api.letsencrypt.org-directory","error":"[files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
{"level":"error","ts":1754912073.7884212,"logger":"tls.obtain","msg":"will retry","error":"[files.avigdol.com] Obtain: [files.avigdol.com] creating new order: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":67.596023469,"max_duration":2592000}
ubuntu@ip-10-0-1-113:~$ curl http://localhost:30019/config/ 2>/dev/null | jq . || echo "Caddy admin API not responding"
ubuntu@ip-10-0-1-113:~$ dig +short passwords.avigdol.com
dig +short files.avigdol.com
54.88.132.35
54.88.132.35
ubuntu@ip-10-0-1-113:~$ curl -4 ifconfig.me
54.88.132.35ubuntu@ip-10sudo netstat -tlnp | grep -E ":80|:443"E ":80|:443"
sudo: netstat: command not found
ubuntu@ip-10-0-1-113:~$ sudo ss -tlnp | grep -E ":80|:443"
ubuntu@ip-10-0-1-113:~$ # Check security group rules (run this from your local machine where terraform is)
aws ec2 describe-security-groups --group-ids $(terraform output -raw security_group_id) --query 'SecurityGroups[0].IpPermissions[*].[FromPort,ToPort,IpProtocol,IpRanges[0].CidrIp]' --output table
terraform: command not found

An error occurred (UnauthorizedOperation) when calling the DescribeSecurityGroups operation: You are not authorized to perform this operation. User: arn:aws:sts::874888505976:assumed-role/homelab-dev-ec2-role/i-06b032c9effbbc144 is not authorized to perform: ec2:DescribeSecurityGroups because no identity-based policy allows the ec2:DescribeSecurityGroups action